### ISSUE TITLE
Nie uruchamia się kernel Pythona3

### ISSUE THREAD

**Issue by jwitczak** [korona-science/intro#2]
Mam problem z uruchomieniem Pythona. Podczas uruchamiania otrzymuję komunikat: 'Dead kernel'. Załączam zrzuty ekranu.

![deadKernelPython](https://user-images.githubusercontent.com/56296079/76688916-b38cc800-6631-11ea-8c5b-10c810b46dd6.jpg)
![deadKernelPython2](https://user-images.githubusercontent.com/56296079/76688919-bab3d600-6631-11ea-8aab-12738ccf4c1c.jpg)

Restartowałam komputer i reinstalowałam cały pakiet od początku, ale nic nie pomaga.

**Comment by RouNNdeL** [comment]
Proszę wkleić cały stack trace błędu z konsoli.

**Comment by jwitczak** [comment]
[deadKernelPython.txt](https://github.com/korona-science/intro/files/4333261/deadKernelPython.txt)
System cały czas próbuje zrestartować kernel, przesyłam bieżący stan.

**Comment by RouNNdeL** [comment]
Proszę spojrzeć tu: https://github.com/jupyter/notebook/issues/1892

**Comment by RouNNdeL** [comment]
Czy udało ci się rozwiązać problem?

**Comment by jwitczak** [comment]
Nadal nie działa. Reinstalowałam kernel poleceniami: 
pip uninstall ipykernel ipython jupyter_client jupyter_core traitlets ipython_genutils -y
pip install ipykernel ipython jupyter_client jupyter_core traitlets ipython_genutils

**Comment by RouNNdeL** [comment]
Spróbuj w takim razie utworzyć środowisko wirtualne używając venv w jakimś konkretnym folderze i za jego pomocą zainstaluj Jupytera i inne modułu. Pamiętaj, że wtedy nie będą one zainstalowane globalnie.
https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/

**Comment by RouNNdeL** [comment]
Ew. możesz użyć jakiegoś gotowego środowiska np. Anaconda lub Mini conda, ale z nimi nie miałem styczności i będziesz sama musiała znaleźć jak to zrobić

**Comment by jwitczak** [comment]
Dzięki, spróbuję

**Comment by RouNNdeL** [comment]
Będę jutro pisał tutorial do Minicondy, bo nie tylko tobie nie działa. Więc jeśli nie chcesz się sama w to bawić to możesz poczekać

**Comment by RouNNdeL** [comment]
Udało się z venv?

**Comment by jwitczak** [comment]
Niestety ten sam rezultat

**Comment by RouNNdeL** [comment]
Spróbuj w takim razie Anaconde lub Miniconde, niestety bez możliwości odtworzenia błedu nie jestem w stanie bardziej ci pomóc
